//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] dontforget {
            get {
                object obj = ResourceManager.GetObject("dontforget", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;Title&quot;: &quot;Deltarune&quot;,
        ///	&quot;Menu_File&quot;: &quot;_Archivo&quot;,
        ///	&quot;Menu_File_Exit&quot;: &quot;_Salir&quot;,
        ///	&quot;Menu_patch_Switch&quot;: &quot;Instalar parche para Nintendo Switch&quot;,
        ///	&quot;Menu_patch_Xbox&quot;: &quot;Instalar parche para Xbox One&quot;,
        ///	&quot;Menu_patch_PC&quot;: &quot;Instalar parche para PC&quot;,
        ///	&quot;Menu_patch_PS4&quot;: &quot;Instalar parche para PS4&quot;,
        ///	&quot;Menu_warning_install&quot;: &quot;¿ACEPTARÁS TODO CUANTO PASE DESDE ESTE MOMENTO?&quot;,
        ///	&quot;Menu_warning_title&quot;: &quot;Warning&quot;,
        ///	&quot;Menu_Confirm&quot;: &quot;Si&quot;,
        ///	&quot;Menu_Decline&quot;: &quot;No&quot;,
        ///	&quot;Error&quot;: &quot;Error&quot;,
        ///	&quot;Menu_Open_File&quot;: &quot;Abrir&quot;
        ///}.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///    &quot;date&quot;: &quot;1540902565549&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_5_0&quot;: &quot; ^9 ^8 %&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_8_0&quot;: &quot;\\M0...&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_125_0&quot;: &quot;\\M0 %&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_6_0&quot;: &quot; ¿ESTÁS^6&amp; AHÍ^6?\\M1 ^6 %&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_7_0&quot;: &quot;^6 \\M0¿ESTAMOS^6&amp;CONECTADOS^6? ^6 %%&quot;,
        ///    &quot;DEVICE_CONTACT_slash_Step_0_gml_33_0&quot;: &quot;\\M0EXCELENTE^4.\\M1 ^6 %&quot;,
        ///    &quot;special_name_check_01&quot;: &quot;SUSIE&quot;,
        ///    &quot;special_name_check_02&quot;: &quot;NOELLE&quot;,
        ///    &quot;speci [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] PC {
            get {
                object obj = ResourceManager.GetObject("PC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] PS4 {
            get {
                object obj = ResourceManager.GetObject("PS4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Xbox {
            get {
                object obj = ResourceManager.GetObject("Xbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
