//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;Title&quot;: &quot;GamePatcher&quot;,
        ///	&quot;Menu_File&quot;: &quot;_File&quot;,
        ///	&quot;Menu_File_Exit&quot;: &quot;_Exit&quot;,
        ///	&quot;Menu_patch_Switch&quot;: &quot;Install Patch for Nintendo Switch&quot;,
        ///	&quot;Menu_patch_Xbox&quot;: &quot;Install Patch for Xbox One&quot;,
        ///	&quot;Menu_patch_PC&quot;: &quot;Install Patch for PC&quot;,
        ///	&quot;Menu_patch_PS4&quot;: &quot;Install Patch for PS4&quot;,
        ///	&quot;Menu_warning_install&quot;: &quot;Are you sure you want to proceed with this?&quot;,
        ///	&quot;Menu_warning_title&quot;: &quot;Warning&quot;,
        ///	&quot;Menu_Confirm&quot;: &quot;Yes&quot;,
        ///	&quot;Menu_Decline&quot;: &quot;No&quot;,
        ///	&quot;Error&quot;: &quot;Error&quot;
        ///}.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;Title&quot;: &quot;GamePatcher&quot;,
        ///	&quot;Menu_File&quot;: &quot;_File&quot;,
        ///	&quot;Menu_File_Exit&quot;: &quot;_Exit&quot;,
        ///	&quot;Menu_patch_Switch&quot;: &quot;Install Patch for Nintendo Switch&quot;,
        ///	&quot;Menu_patch_Xbox&quot;: &quot;Install Patch for Xbox One&quot;,
        ///	&quot;Menu_patch_PC&quot;: &quot;Install Patch for PC&quot;,
        ///	&quot;Menu_patch_PS4&quot;: &quot;Install Patch for PS4&quot;,
        ///	&quot;Menu_warning_install&quot;: &quot;Are you sure you want to proceed with this?&quot;,
        ///	&quot;Menu_warning_title&quot;: &quot;Warning&quot;,
        ///	&quot;Menu_Confirm&quot;: &quot;Yes&quot;,
        ///	&quot;Menu_Decline&quot;: &quot;No&quot;,
        ///	&quot;Error&quot;: &quot;Error&quot;
        ///}.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] PC {
            get {
                object obj = ResourceManager.GetObject("PC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] PS4 {
            get {
                object obj = ResourceManager.GetObject("PS4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Xbox {
            get {
                object obj = ResourceManager.GetObject("Xbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
